# Default values for devcontainer-workspace.
# This is a YAML-formatted file.

global:
  registry: registry.k8s.mrv.thebends.org
  domainSuffix: k8s.mrv.thebends.org
  storageClass: local-hostpath
  sshKeySecret: ssh-public-keys
  sshTargetPort: 2222
  builder:
    image: node:24-bookworm-slim
    dindImage: docker:29-dind

workspaceName: ""
git:
  url: ""
  directory: ""
storage:
  size: 20Gi
image:
  repository: ""
  tag: latest
builder:
  enabled: true
  cacheFrom: []

features:
  registry.k8s.mrv.thebends.org/devcontainers/antigravity:1: {}
  ghcr.io/devcontainers/features/sshd:1: {}

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    memory: "16Gi"

nodeSelector: {}
tolerations: []
