---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ical
  namespace: devcontainers
spec:
  wait: false
  releaseName: ical
  chart:
    spec:
      chart: ./kubernetes/devcontainers/charts/devcontainer-workspace
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    workspaceName: ical
    git:
      url: https://github.com/allenporter/ical.git
      directory: ical
    storage:
      size: 10Gi
    image:
      tag: latest
    builder:
      enabled: true
