---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: repo-conformance
  namespace: devcontainers
spec:
  releaseName: repo-conformance
  chart:
    spec:
      chart: ./kubernetes/devcontainers/charts/devcontainer-workspace
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
  values:
    workspaceName: repo-conformance
    git:
      url: https://github.com/allenporter/repo-conformance.git
      directory: repo-conformance
    storage:
      size: 10Gi
    image:
      repository: mcr.microsoft.com/devcontainers/python
      tag: 3.14-bookworm
    builder:
      enabled: false
