---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ws-platform
  namespace: devcontainers
  annotations:
    devcontainer.purpose: "Kubernetes GitOps infrastructure, cluster Helm charts, DevContainer feature development, and repository conformance tooling."
spec:
  releaseName: ws-platform
  chart:
    spec:
      chart: ./kubernetes/devcontainers/charts/devcontainer-workspace
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
  values:
    workspaceName: platform
    git:
      url: https://github.com/allenporter/k8s-gitops.git
      directory: platform
    storage:
      size: 30Gi
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        memory: "8Gi"
    image:
      repository: registry.k8s.mrv.thebends.org/devcontainers/icaldav
      tag: latest
    builder:
      enabled: true
