---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: intel-device-plugin-values.yaml
- path: intel-device-plugin-gpu-values.yaml
- path: node-feature-discovery-values.yaml
- path: nvidia-device-plugin-values.yaml
- path: actions-runner-controller-values.yaml
- path: actions-runner-scale-set-values.yaml
resources:
- ../base/intel-device-plugin
- ../base/intel-device-plugin-gpu
- ../base/node-feature-discovery
- ../base/nvidia-device-plugin
- ../base/actions-runner-controller
- ../base/actions-runner-scale-set
- system-upgrade-controller
- nvidia-time-slicing-config.yaml
- github-app-credentials.sops.yaml
- actions-runner-controller-rbac.yaml
