---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 10Gi
