---
apiVersion: v1
kind: Service
metadata:
  name: workspace-temp-service
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 2222
    protocol: TCP
    name: ssh
  selector:
    app: workspace-temp
