---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-shelf-ceph
  namespace: unifi
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
