---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-ring-keypad
  namespace: devcontainers
  labels:
    app: ws-ring-keypad
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ws-ring-keypad
  template:
    metadata:
      labels:
        app: ws-ring-keypad
    spec:
      containers:
      - name: workspace
        image: registry.k8s.mrv.thebends.org/devcontainers/home-assistant-ring-keypad:latest
        workingDir: /workspaces/home-assistant-ring-keypad
        command: ["/bin/sh", "-c"]
        args:
        - |
            if ! command -v sshd >/dev/null 2>&1; then
              echo "sshd not found. Installing openssh-server..."
              sudo apt-get update && sudo apt-get install -y openssh-server
            fi
            sudo mkdir -p /home/vscode/.ssh
            sudo cp /tmp/ssh-keys/authorized_keys /home/vscode/.ssh/authorized_keys
            sudo chown -R vscode:vscode /home/vscode/.ssh
            sudo chmod 700 /home/vscode/.ssh
            sudo chmod 600 /home/vscode/.ssh/authorized_keys
            sudo chown -R vscode:vscode /workspaces
            sudo ssh-keygen -A
            sudo mkdir -p /var/run/sshd
            sudo /usr/sbin/sshd -D -p 2222
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                if [ ! -d /workspaces/home-assistant-ring-keypad/.git ]; then
                  echo "Cloning..."
                  git clone https://github.com/allenporter/home-assistant-ring-keypad.git /workspaces/home-assistant-ring-keypad
                  chown -R vscode:vscode /workspaces/home-assistant-ring-keypad
                fi
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspaces/home-assistant-ring-keypad
        - name: ssh-keys
          mountPath: /tmp/ssh-keys
          readOnly: true
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: ws-ring-keypad-pvc
      - name: ssh-keys
        secret:
          secretName: ssh-public-keys
          defaultMode: 0o600
