---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-{{ .Values.workspaceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ws-{{ .Values.workspaceName }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ws-{{ .Values.workspaceName }}
  template:
    metadata:
      labels:
        app: ws-{{ .Values.workspaceName }}
    spec:
      containers:
      - name: workspace
        image: "{{ .Values.global.registry }}/devcontainers/{{ .Values.git.directory }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        workingDir: /workspaces/{{ .Values.git.directory }}
        command: ["/bin/sh", "-c"]
        args:
        - |
            if ! command -v sshd >/dev/null 2>&1; then
              echo "sshd not found. Installing openssh-server..."
              sudo apt-get update && sudo apt-get install -y openssh-server
            fi
            sudo mkdir -p /home/vscode/.ssh
            sudo cp /tmp/ssh-keys/authorized_keys /home/vscode/.ssh/authorized_keys
            sudo chown -R vscode:vscode /home/vscode/.ssh
            sudo chmod 700 /home/vscode/.ssh
            sudo chmod 600 /home/vscode/.ssh/authorized_keys
            sudo chown -R vscode:vscode /workspaces
            sudo ssh-keygen -A
            sudo mkdir -p /var/run/sshd
            sudo /usr/sbin/sshd -D -p {{ .Values.global.sshTargetPort }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                if [ ! -d /workspaces/{{ .Values.git.directory }}/.git ]; then
                  echo "Cloning..."
                  git clone {{ .Values.git.url }} /workspaces/{{ .Values.git.directory }}
                  chown -R vscode:vscode /workspaces/{{ .Values.git.directory }}
                fi
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspaces/{{ .Values.git.directory }}
        - name: ssh-keys
          mountPath: /tmp/ssh-keys
          readOnly: true
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: ws-{{ .Values.workspaceName }}-pvc
      - name: ssh-keys
        secret:
          secretName: {{ .Values.global.sshKeySecret | quote }}
          defaultMode: 0o600
