---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-{{ .Values.workspaceName }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
