---
apiVersion: v1
kind: Service
metadata:
  name: ws-{{ .Values.workspaceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    coredns.io/hostname: ws-{{ .Values.workspaceName }}.{{ .Values.global.domainSuffix }}
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: {{ .Values.global.sshTargetPort }}
    protocol: TCP
    name: ssh
  - port: 52425
    targetPort: 52425
    protocol: TCP
    name: antigravity-https
  - port: 43635
    targetPort: 43635
    protocol: TCP
    name: antigravity-http
  selector:
    app: ws-{{ .Values.workspaceName }}
