---
apiVersion: v1
kind: Service
metadata:
  name: ws-{{ .Values.workspaceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: {{ .Values.global.sshTargetPort }}
    protocol: TCP
    name: ssh
  - port: 52425
    targetPort: 43635
    protocol: TCP
    name: antigravity-http
  selector:
    app: ws-{{ .Values.workspaceName }}
