---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  releaseName: gha-runner-scale-set
  chart:
    spec:
      chart: gha-runner-scale-set
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    githubConfigUrl: "https://github.com/allenporter/k8s-gitops"
    githubConfigSecret: github-app-credentials
    minRunners: 0
    maxRunners: 5
    containerMode:
      type: "dind"
