apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:j/MVeeMdwTpXMiGZb4ij9fpu2tMBjczgMDMprR7EwQ8yQex+etreHA==,iv:Z6brh6byA/zYvxzKdKVHiIgDpjTI1M38rER5aHmQ4FA=,tag:l0jRnLHEctM5byNAmkQAhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK3pXWkFWTE9weXNZZnJB
            SUF0Ym93TTVqQlRYd3p1L0pPeVZKT3p0dVFFCmVqTnU3TGhXajlINFlnTXkwL3A2
            T0l6YWlSajBVbVJFanBZYTdWbitDUFUKLS0tIDVtalRZVGx1QWdENElXL0NPbHJy
            ZVhxOVV4RWs2UDBNMnFsZXJNaWZvU0EKW3ibp/MZyCPJiMevtUX4ZhYFtoanuxC9
            7b1SOzfkNrgAYTYoSYbf/fqVKTSw7cubHQNmVE1SqS6VaBxZu4aCjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:41:55Z"
    mac: ENC[AES256_GCM,data:kUNbw/4sxbkuJheRv7P25DUyDFiArR8ntRhTCRHi6OYHX/Xq4UhaSEhZJrXxa6J/v5ekoJ6Oj1+luBwDrzRs3YhtL0/7JblC5XMMUiWA2AUW8a9IWVUbbduFavYYpMGDgv7sB6Y5QjwEu1Gvaa7V9ZS5n+EzHFphQfbcnAk5o3E=,iv:aoQuIRnY8/aXye7/QZnZ/eLpRhEJ+0yvwj3pdHchQdM=,tag:ccZW4Rc8fRdudLt9EnIFMg==,type:str]
    version: 3.13.1
