---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/workspace-template
namePrefix: ha-core-
labels:
  - pairs:
      app: ha-core-workspace-temp
patches:
  - path: patch.yaml
