---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-temp
spec:
  template:
    spec:
      containers:
      - name: workspace
        image: mcr.microsoft.com/devcontainers/python:3.14-bookworm
        workingDir: /workspaces/home-assistant-core
        args:
        - |
            if ! command -v sshd >/dev/null 2>&1; then
              echo "sshd not found. Installing openssh-server..."
              sudo apt-get update && sudo apt-get install -y openssh-server
            fi
            sudo ssh-keygen -A
            sudo mkdir -p /var/run/sshd
            sudo /usr/sbin/sshd -D -p 2222
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "devcontainer run-user-commands --workspace-folder /workspaces/home-assistant-core"]
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspaces/home-assistant-core
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-temp-service
  annotations:
    coredns.io/hostname: home-assistant-core.devcontainers.k8s.mrv.thebends.org
spec:
  selector:
    app: ha-core-workspace-temp
