---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devcontainers
resources:
  - ../base
  - ssh-public-keys.yaml
  - prepuller.yaml
  - workspaces/google-health-api
  - workspaces/ring-keypad
  - workspaces/home-assistant-core
  - workspaces/journal-assistant
