---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devcontainers
resources:
  - ../base
  - ssh-public-keys.yaml
  - workspaces/google-health-api-release.yaml
  - workspaces/home-assistant-core-release.yaml
  - workspaces/home-assistant-datasets-release.yaml
  - workspaces/repo-conformance-release.yaml
  - workspaces/ical-release.yaml
  - workspaces/pyrainbird-release.yaml
  - workspaces/ring-keypad-release.yaml
  - workspaces/journal-assistant-release.yaml
