---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: antigravity-shared-keyring-pvc
  namespace: devcontainers
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 1Gi
