---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-public-keys
  namespace: devcontainers
type: Opaque
stringData:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMgapzKxl5psYtNtqE5E7gJt6WC6677ClsT4S9fsx3Lk allen@thebends.org
