name: Flux Diff
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.yaml"
jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
          - kubernetes/clusters/prod
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
      - name: Checkout Baseline Branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: baseline-repo
      - name: Setup flate CLI
        uses: home-operations/flate/action@v0.4.10
      - name: Run flate diff
        id: diff
        run: |
          diff_output=$(flate diff all --path ${{ matrix.cluster_path }} --path-orig baseline-repo/${{ matrix.cluster_path }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$diff_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: PR Comments
        uses: mshick/add-pr-comment@v3
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}
          message-failure: Unable to post diff
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
