---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  flux_tests:
    strategy:
      matrix:
        cluster_path:
          - kubernetes/clusters/prod
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup flate CLI
        uses: home-operations/flate/action@v0.4.10
        with:
          base: ""
      - name: Run flate test
        run: |
          flate test all --path ${{ matrix.cluster_path }}
