---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-google-health-api-pvc
  namespace: devcontainers
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 10Gi
