---
apiVersion: v1
kind: Service
metadata:
  name: ws-google-health-api
  namespace: devcontainers
  annotations:
    coredns.io/hostname: ws-google-health-api.devcontainers.k8s.mrv.thebends.org
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 2222
    protocol: TCP
    name: ssh
  selector:
    app: ws-google-health-api
